"""refactor_menus_and_order_items

Revision ID: 05a9f551b64e
Revises: 1bfc529c7d3b
Create Date: 2026-09-29 00:46:59.828071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a9f551b64e'
down_revision: Union[str, Sequence[str], None] = '1bfc529c7d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('menu_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('menu_item_id', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['room_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('room_service_orders', sa.Column('total_amount', sa.Float(), nullable=False, server_default='0.0'))

    # 1. Seed Menus
    op.execute("""
        INSERT INTO menus (id, name, category, description, is_active, created_at, updated_at)
        VALUES 
            ('MENU-ALLDAY', 'Thực đơn Gọi Món All-Day Dining', 'Food', 'Phục vụ bữa trưa, tối và món ăn nhẹ tại phòng 24/7', true, NOW(), NOW()),
            ('MENU-BREAKFAST', 'Thực đơn Điểm Tâm Sáng', 'Food', 'Phục vụ các món điểm tâm sáng nóng hổi từ 06:00 đến 10:30', true, NOW(), NOW()),
            ('MENU-BEVERAGE', 'Menu Đồ Uống & Cocktail', 'Beverage', 'Cà phê nguyên chất, nước ép tươi, trà và cocktail chọn lọc', true, NOW(), NOW()),
            ('MENU-DESSERT', 'Thực đơn Tráng Miệng & Bánh Ngọt', 'Dessert', 'Các món bánh Pháp và tráng miệng thanh mát', true, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 2. Seed Menu Items
    op.execute("""
        INSERT INTO menu_items (id, menu_id, name, price, currency, image_url, category, is_available, prep_time_minutes, description, created_at, updated_at)
        VALUES 
            ('ITEM-SANDWICH', 'MENU-ALLDAY', 'Club Sandwich & Truffle Fries', 185000, 'VND', '/static/menu/club_sandwich.jpg', 'Món chính', true, 15, 'Bánh mì sandwich kẹp thịt nguội, phô mai cheddar và khoai tây chiên sốt nấm truffle', NOW(), NOW()),
            ('ITEM-WAGYU-BURGER', 'MENU-ALLDAY', 'Burger Bò Wagyu Nướng Phô Mai', 260000, 'VND', '/static/menu/wagyu_burger.jpg', 'Món chính', true, 20, 'Thịt bò Wagyu 180g nướng than hoa, sốt BBQ đặc biệt và khoai tây múi cau', NOW(), NOW()),
            ('ITEM-SALAD-CAESAR', 'MENU-ALLDAY', 'Caesar Salad Lườn Gà Áp Chảo', 145000, 'VND', '/static/menu/caesar_salad.jpg', 'Khai vị', true, 12, 'Xà lách romaine, sốt caesar truyền thống, bánh mì giòn và phô mai parmesan', NOW(), NOW()),
            ('ITEM-SPAGHETTI', 'MENU-ALLDAY', 'Mì Ý Sốt Bò Bằm Bolognese', 195000, 'VND', '/static/menu/spaghetti.jpg', 'Món chính', true, 18, 'Mì spaghetti truyền thống sốt thịt bò bằm hầm rượu vang đỏ', NOW(), NOW()),
            
            ('ITEM-PHO-BO', 'MENU-BREAKFAST', 'Phở Bò Tái Nạm Wagyu', 175000, 'VND', '/static/menu/pho_bo.jpg', 'Món chính', true, 15, 'Nước dùng hầm xương 24h gia truyền, bò nạm mềm và bắp hoa tươi', NOW(), NOW()),
            ('ITEM-BANH-MI', 'MENU-BREAKFAST', 'Bánh Mì Thịt Nguội Pâté Cột Đèn', 75000, 'VND', '/static/menu/banh_mi.jpg', 'Món chính', true, 10, 'Bánh mì giòn rụm với pâté béo ngậy, chả lụa hảo hạng và đồ chua', NOW(), NOW()),
            ('ITEM-EGG-BENEDICT', 'MENU-BREAKFAST', 'Trứng Chần Eggs Benedict', 160000, 'VND', '/static/menu/egg_benedict.jpg', 'Món chính', true, 15, 'Bánh muffin nướng, thịt hun khói, trứng chần lòng đào sốt hollandaise', NOW(), NOW()),
            
            ('ITEM-CAFE-SUA', 'MENU-BEVERAGE', 'Cà Phê Sữa Đá Sài Gòn', 55000, 'VND', '/static/menu/cafe_sua.jpg', 'Đồ uống', true, 5, 'Hạt cà phê Robusta Buôn Ma Thuột rang mộc pha phin đậm đà', NOW(), NOW()),
            ('ITEM-CAFE-MUOI', 'MENU-BEVERAGE', 'Cà Phê Muối Cố Đô', 65000, 'VND', '/static/menu/cafe_muoi.jpg', 'Đồ uống', true, 7, 'Cà phê pha phin truyền thống phủ lớp kem muối béo ngậy thơm ngon', NOW(), NOW()),
            ('ITEM-JUICE-ORANGE', 'MENU-BEVERAGE', 'Nước Ép Cam Tươi Nguyên Chất', 65000, 'VND', '/static/menu/orange_juice.jpg', 'Đồ uống', true, 8, 'Cam sành mọng nước ép trực tiếp thanh mát', NOW(), NOW()),
            ('ITEM-COCKTAIL-SUNSET', 'MENU-BEVERAGE', 'Cocktail Horizon Sunset', 145000, 'VND', '/static/menu/cocktail.jpg', 'Đồ uống', true, 10, 'Gin hảo hạng kết hợp nước ép bưởi hồng, syrup hoa hồng và tonic', NOW(), NOW()),
            
            ('ITEM-TIRAMISU', 'MENU-DESSERT', 'Bánh Tiramisu Ý Cổ Điển', 95000, 'VND', '/static/menu/tiramisu.jpg', 'Tráng miệng', true, 5, 'Bánh quy ladyfinger nhúng espresso, kem mascarpone và cacao Valrhona', NOW(), NOW()),
            ('ITEM-PANNA-COTTA', 'MENU-DESSERT', 'Panna Cotta Sốt Dâu Rừng', 85000, 'VND', '/static/menu/panna_cotta.jpg', 'Tráng miệng', true, 5, 'Thạch kem sữa mềm mịn béo ngậy kèm sốt dâu rừng chua ngọt', NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 3. Backfill order_items from existing room_service_orders.items JSON
    op.execute("""
        DO $$
        DECLARE
            rec RECORD;
            itm JSONB;
            m_id VARCHAR(50);
            u_price FLOAT;
            s_total FLOAT;
            ord_total FLOAT;
        BEGIN
            FOR rec IN SELECT id, items FROM room_service_orders WHERE items IS NOT NULL LOOP
                ord_total := 0.0;
                IF jsonb_typeof(rec.items::jsonb) = 'array' THEN
                    FOR itm IN SELECT * FROM jsonb_array_elements(rec.items::jsonb) LOOP
                        m_id := NULL;
                        u_price := 150000.0;

                        IF (itm->>'name') ILIKE '%Sandwich%' THEN
                            m_id := 'ITEM-SANDWICH';
                            u_price := 185000.0;
                        ELSIF (itm->>'name') ILIKE '%Burger%' THEN
                            m_id := 'ITEM-WAGYU-BURGER';
                            u_price := 260000.0;
                        ELSIF (itm->>'name') ILIKE '%Phở%' OR (itm->>'name') ILIKE '%Pho%' THEN
                            m_id := 'ITEM-PHO-BO';
                            u_price := 175000.0;
                        ELSIF (itm->>'name') ILIKE '%Cà phê%' OR (itm->>'name') ILIKE '%Coffee%' THEN
                            m_id := 'ITEM-CAFE-SUA';
                            u_price := 55000.0;
                        ELSE
                            m_id := 'ITEM-SANDWICH';
                            u_price := 185000.0;
                        END IF;

                        s_total := COALESCE((itm->>'qty')::int, 1) * u_price;
                        ord_total := ord_total + s_total;

                        INSERT INTO order_items (order_id, menu_item_id, item_name, quantity, unit_price, subtotal, notes, created_at)
                        VALUES (
                            rec.id, 
                            m_id, 
                            COALESCE(itm->>'name', 'Room Service Item'), 
                            COALESCE((itm->>'qty')::int, 1), 
                            u_price, 
                            s_total, 
                            'Tự động đồng bộ từ đơn hàng cũ', 
                            NOW()
                        );
                    END LOOP;
                END IF;

                UPDATE room_service_orders
                SET total_amount = ord_total
                WHERE id = rec.id;
            END LOOP;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_service_orders', 'total_amount')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_menu_items_menu_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_table('menus')
    # ### end Alembic commands ###
