"""refactor_hotel_map_and_telemetry

Revision ID: 1bfc529c7d3b
Revises: bd6b3a75b7a6
Create Date: 2026-09-29 00:25:01.722612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bfc529c7d3b'
down_revision: Union[str, Sequence[str], None] = 'bd6b3a75b7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_groups',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hotel_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_hotel_id'), 'events', ['hotel_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hotel_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('open_time', sa.String(length=20), nullable=False),
    sa.Column('close_time', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_hotel_id'), 'facilities', ['hotel_id'], unique=False)
    op.create_table('maps',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hotel_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('origin_x', sa.Float(), nullable=False),
    sa.Column('origin_y', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_hotel_id'), 'maps', ['hotel_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hotel_id', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_guest_name', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=True)
    op.create_table('telemetries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(length=50), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('yaw', sa.Float(), nullable=False),
    sa.Column('linear_velocity', sa.Float(), nullable=False),
    sa.Column('angular_velocity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetries_recorded_at'), 'telemetries', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_telemetries_robot_id'), 'telemetries', ['robot_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('yaw', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_map_id'), 'endpoints', ['map_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('map_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('speed_limit', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_map_id'), 'zones', ['map_id'], unique=False)
    op.create_table('endpoint_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint_group_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_group_id'], ['endpoint_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_group_members_endpoint_group_id'), 'endpoint_group_members', ['endpoint_group_id'], unique=False)
    op.create_index(op.f('ix_endpoint_group_members_endpoint_id'), 'endpoint_group_members', ['endpoint_id'], unique=False)
    # 1. Seed default hotel
    op.execute("""
        INSERT INTO hotels (id, name, address, phone, email, star_rating, description, is_active, created_at, updated_at)
        VALUES ('HTL-MAIN', 'HC Grand Hotel & Suites', '123 Đ. Sáng Tạo, Q.9, TP.HCM', '+84 28 3730 0000', 'contact@hcgrandhotel.com', 5, 'Khách sạn thông minh 5 sao tích hợp Robot Concierge', true, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 2. Seed default map
    op.execute("""
        INSERT INTO maps (id, hotel_id, name, floor, resolution, width, height, origin_x, origin_y, is_active, created_at, updated_at)
        VALUES ('MAP-LOBBY-01', 'HTL-MAIN', 'Bản đồ Sảnh Tầng 1 Main Lobby', 'Sảnh Tầng 1', 0.05, 200, 200, -5.0, -5.0, true, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 3. Seed common hotel rooms
    op.execute("""
        INSERT INTO rooms (id, hotel_id, room_number, floor, room_type, status, description, created_at, updated_at)
        VALUES 
            ('ROOM-105', 'HTL-MAIN', '105', 'Tầng 1', 'Superior Room', 'OCCUPIED', 'Phòng tiêu chuẩn tầng 1 gần sảnh', NOW(), NOW()),
            ('ROOM-201', 'HTL-MAIN', '201', 'Tầng 2', 'Deluxe Room', 'OCCUPIED', 'Phòng Deluxe hướng hồ bơi', NOW(), NOW()),
            ('ROOM-300', 'HTL-MAIN', '300', 'Tầng 3', 'Executive Suite', 'OCCUPIED', 'Phòng Executive tầng 3', NOW(), NOW()),
            ('ROOM-304', 'HTL-MAIN', '304', 'Tầng 3', 'Deluxe Room', 'OCCUPIED', 'Phòng Deluxe tầng 3', NOW(), NOW()),
            ('ROOM-305', 'HTL-MAIN', '305', 'Tầng 3', 'Deluxe Room', 'AVAILABLE', 'Phòng Deluxe tầng 3', NOW(), NOW()),
            ('ROOM-308', 'HTL-MAIN', '308', 'Tầng 3', 'Superior Room', 'OCCUPIED', 'Phòng Superior tầng 3', NOW(), NOW()),
            ('ROOM-401', 'HTL-MAIN', '401', 'Tầng 4', 'Deluxe Suite', 'AVAILABLE', 'Phòng Deluxe tầng 4', NOW(), NOW()),
            ('ROOM-402', 'HTL-MAIN', '402', 'Tầng 4', 'Presidential Suite', 'OCCUPIED', 'Phòng Suite tổng thống sang trọng', NOW(), NOW()),
            ('ROOM-502', 'HTL-MAIN', '502', 'Tầng 5', 'Deluxe Suite', 'OCCUPIED', 'Phòng Deluxe Suite tầng 5', NOW(), NOW()),
            ('ROOM-603', 'HTL-MAIN', '603', 'Tầng 6', 'Penthouse', 'OCCUPIED', 'Penthouse tầng 6 view toàn cảnh thành phố', NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 4. Seed hotel facilities
    op.execute("""
        INSERT INTO facilities (id, hotel_id, name, category, location, open_time, close_time, description, is_active, created_at, updated_at)
        VALUES 
            ('FAC-POOL', 'HTL-MAIN', 'Bể bơi vô cực Horizon Pool', 'Recreation', 'Tầng 5', '06:00', '22:00', 'Bể bơi vô cực ngoài trời với tầm nhìn panorama', true, NOW(), NOW()),
            ('FAC-GYM', 'HTL-MAIN', 'Trung tâm Thể hình & Gym FitLife', 'Wellness', 'Tầng 3', '06:00', '23:00', 'Phòng gym trang bị thiết bị hiện đại Technogym', true, NOW(), NOW()),
            ('FAC-SPA', 'HTL-MAIN', 'Lotus Luxury Spa & Wellness', 'Wellness', 'Tầng 4', '08:00', '22:00', 'Liệu trình massage và thư giãn cao cấp', true, NOW(), NOW()),
            ('FAC-REST', 'HTL-MAIN', 'Nhà hàng Á - Âu Sky Dining', 'Dining', 'Tầng 2', '06:00', '22:30', 'Phục vụ buffet sáng và thực đơn gọi món sang trọng', true, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 5. Seed events
    op.execute("""
        INSERT INTO events (id, hotel_id, title, location, start_time, end_time, description, is_active, created_at, updated_at)
        VALUES 
            ('EVT-COCKTAIL', 'HTL-MAIN', 'Tiệc Cocktail Chào mừng Khách VIP', 'Sky Lounge Tầng 19', NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day 3 hours', 'Đêm tiệc cocktail và âm nhạc acoustic giao lưu khách lưu trú', true, NOW(), NOW()),
            ('EVT-PIANO', 'HTL-MAIN', 'Đêm Nhạc Piano Thư Giãn', 'Lobby Lounge', NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days 2 hours', 'Biểu diễn độc tấu piano cổ điển tại sảnh', true, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    # 6. Migrate data from robot_waypoints to endpoints
    op.execute("""
        INSERT INTO endpoints (id, map_id, name, floor, x, y, yaw, type, description, created_at, updated_at)
        SELECT id, 'MAP-LOBBY-01', name, floor, x, y, yaw, type, description, created_at, updated_at
        FROM robot_waypoints
        ON CONFLICT (id) DO NOTHING;
    """)

    # 7. Migrate data from robot_zones to zones
    op.execute("""
        INSERT INTO zones (id, map_id, name, type, x, y, width, height, speed_limit, floor, description, created_at, updated_at)
        SELECT id, 'MAP-LOBBY-01', name, type, x, y, width, height, speed_limit, floor, description, created_at, updated_at
        FROM robot_zones
        ON CONFLICT (id) DO NOTHING;
    """)

    # 8. Seed endpoint groups & memberships
    op.execute("""
        INSERT INTO endpoint_groups (id, name, description, created_at, updated_at)
        VALUES 
            ('GRP-LOBBY', 'Khu vực Sảnh Chính', 'Các điểm dừng dịch vụ tại sảnh chính Tầng 1', NOW(), NOW()),
            ('GRP-CHARGING', 'Trạm Năng Lượng', 'Khu vực sạc pin tự động cho robot', NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)
    op.execute("""
        INSERT INTO endpoint_group_members (endpoint_id, endpoint_group_id, created_at)
        SELECT id, 'GRP-LOBBY', NOW()
        FROM endpoints
        WHERE id IN ('wp-reception', 'wp-lounge', 'wp-vip-table')
        ON CONFLICT DO NOTHING;
    """)

    # 9. Seed telemetry ping for robot
    op.execute("""
        INSERT INTO telemetries (robot_id, battery_level, x, y, yaw, linear_velocity, angular_velocity, status, recorded_at)
        SELECT id, battery_level, 0.0, 0.0, 0.0, 0.0, 0.0, status, NOW()
        FROM robots
        WHERE id = 'RC-001' OR code = 'ROBOT-01'
        LIMIT 1;
    """)

    # 10. Drop legacy tables
    op.drop_table('robot_waypoints')
    op.drop_table('robot_zones')

    # 11. Add columns to room_service_orders and support_requests
    op.add_column('room_service_orders', sa.Column('room_id', sa.String(length=50), nullable=True))
    op.add_column('room_service_orders', sa.Column('account_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_room_service_orders_account_id'), 'room_service_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_room_service_orders_room_id'), 'room_service_orders', ['room_id'], unique=False)
    op.create_foreign_key('fk_room_service_orders_account_id', 'room_service_orders', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_room_service_orders_room_id', 'room_service_orders', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')

    op.add_column('support_requests', sa.Column('room_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_support_requests_room_id'), 'support_requests', ['room_id'], unique=False)
    op.create_foreign_key('fk_support_requests_room_id', 'support_requests', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')

    # 12. Backfill room_id
    op.execute("""
        UPDATE support_requests sr
        SET room_id = r.id
        FROM rooms r
        WHERE sr.room_id IS NULL AND (
            sr.room_number = r.room_number 
            OR sr.room_number = ('Phòng ' || r.room_number)
            OR sr.room_number LIKE ('%' || r.room_number || '%')
        );
    """)
    op.execute("""
        UPDATE room_service_orders rso
        SET room_id = r.id
        FROM rooms r
        WHERE rso.room_id IS NULL AND (
            rso.room_number = r.room_number 
            OR rso.room_number = ('Phòng ' || r.room_number)
            OR rso.room_number LIKE ('%' || r.room_number || '%')
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_support_requests_room_id', 'support_requests', type_='foreignkey')
    op.drop_index(op.f('ix_support_requests_room_id'), table_name='support_requests')
    op.drop_column('support_requests', 'room_id')
    op.drop_constraint('fk_room_service_orders_room_id', 'room_service_orders', type_='foreignkey')
    op.drop_constraint('fk_room_service_orders_account_id', 'room_service_orders', type_='foreignkey')
    op.drop_index(op.f('ix_room_service_orders_room_id'), table_name='room_service_orders')
    op.drop_index(op.f('ix_room_service_orders_account_id'), table_name='room_service_orders')
    op.drop_column('room_service_orders', 'account_id')
    op.drop_column('room_service_orders', 'room_id')
    op.create_table('robot_zones',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_zones_pkey'))
    )
    op.create_table('robot_waypoints',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('yaw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_waypoints_pkey'))
    )
    op.drop_index(op.f('ix_endpoint_group_members_endpoint_id'), table_name='endpoint_group_members')
    op.drop_index(op.f('ix_endpoint_group_members_endpoint_group_id'), table_name='endpoint_group_members')
    op.drop_table('endpoint_group_members')
    op.drop_index(op.f('ix_zones_map_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_endpoints_map_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_telemetries_robot_id'), table_name='telemetries')
    op.drop_index(op.f('ix_telemetries_recorded_at'), table_name='telemetries')
    op.drop_table('telemetries')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_maps_hotel_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_facilities_hotel_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_events_hotel_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('hotels')
    op.drop_table('endpoint_groups')
    # ### end Alembic commands ###
