"""initial_schema_after_cleanup

Revision ID: 87055640bdf0
Revises: 
Create Date: 2026-09-12 22:48:00.260921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87055640bdf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Drop foreign key constraints referencing robot_units first
    op.drop_constraint(op.f('bell_requests_assigned_robot_id_fkey'), 'bell_requests', type_='foreignkey')
    op.drop_constraint(op.f('room_service_orders_assigned_robot_id_fkey'), 'room_service_orders', type_='foreignkey')

    # 2. Drop removed tables
    op.drop_index(op.f('ix_restaurant_reservations_reservation_code'), table_name='restaurant_reservations')
    op.drop_table('restaurant_reservations')
    op.drop_index(op.f('ix_restaurant_pre_orders_order_code'), table_name='restaurant_pre_orders')
    op.drop_table('restaurant_pre_orders')
    op.drop_index(op.f('ix_robot_units_unit_code'), table_name='robot_units')
    op.drop_table('robot_units')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('room_service_orders_assigned_robot_id_fkey'), 'room_service_orders', 'robot_units', ['assigned_robot_id'], ['id'])
    op.create_foreign_key(op.f('bell_requests_assigned_robot_id_fkey'), 'bell_requests', 'robot_units', ['assigned_robot_id'], ['id'])
    op.create_table('robot_units',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_payload', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_units_pkey'))
    )
    op.create_index(op.f('ix_robot_units_unit_code'), 'robot_units', ['unit_code'], unique=True)
    op.create_table('restaurant_pre_orders',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reservation_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guest_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_pre_orders_pkey'))
    )
    op.create_index(op.f('ix_restaurant_pre_orders_order_code'), 'restaurant_pre_orders', ['order_code'], unique=True)
    op.create_table('robot_zones',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_zones_pkey'))
    )
    op.create_table('restaurant_reservations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reservation_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guest_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('party_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reservation_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('special_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_reservations_pkey'))
    )
    op.create_index(op.f('ix_restaurant_reservations_reservation_code'), 'restaurant_reservations', ['reservation_code'], unique=True)
    op.create_table('robot_workflows',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_workflows_pkey'))
    )
    op.create_table('robot_waypoints',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('yaw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('robot_waypoints_pkey'))
    )
    # ### end Alembic commands ###
