"""drop_telemetries_table

Revision ID: c20a2d32e19b
Revises: 05a9f551b64e
Create Date: 2026-09-29 10:06:47.172766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c20a2d32e19b'
down_revision: Union[str, Sequence[str], None] = '05a9f551b64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetries_recorded_at'), table_name='telemetries')
    op.drop_index(op.f('ix_telemetries_robot_id'), table_name='telemetries')
    op.drop_table('telemetries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('yaw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('linear_velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('angular_velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], name=op.f('telemetries_robot_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetries_pkey'))
    )
    op.create_index(op.f('ix_telemetries_robot_id'), 'telemetries', ['robot_id'], unique=False)
    op.create_index(op.f('ix_telemetries_recorded_at'), 'telemetries', ['recorded_at'], unique=False)
    # ### end Alembic commands ###
