#!/usr/bin/env python3
"""
Convert ROS 2 Nav2 Map (.yaml + .pgm) to HC-Robot Web Occupancy Grid JSON.
Allows maps generated by SLAM Toolbox / Nav2 to be loaded directly on Web Admin.
"""

import os
import sys
import yaml
import json
from PIL import Image

if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

def convert_nav2_map_to_json(yaml_path: str, output_json_path: str, map_id: str = None, name: str = None, floor: str = "Tầng 1"):
    if not os.path.exists(yaml_path):
        raise FileNotFoundError(f"Không tìm thấy file: {yaml_path}")

    with open(yaml_path, "r", encoding="utf-8") as f:
        meta = yaml.safe_load(f)

    yaml_dir = os.path.dirname(os.path.abspath(yaml_path))
    image_rel = meta.get("image", "")
    pgm_path = os.path.join(yaml_dir, image_rel)
    if not os.path.exists(pgm_path):
        raise FileNotFoundError(f"Không tìm thấy file PGM: {pgm_path}")

    resolution = float(meta.get("resolution", 0.05))
    origin = meta.get("origin", [-5.0, -5.0, 0.0])
    origin_x = float(origin[0])
    origin_y = float(origin[1])
    negate = int(meta.get("negate", 0))
    occupied_thresh = float(meta.get("occupied_thresh", 0.65))
    free_thresh = float(meta.get("free_thresh", 0.196))

    img = Image.open(pgm_path).convert("L")
    # ROS 2 map_server saves row 0 as top of image, but OccupancyGrid (0,0) is at bottom-left
    img = img.transpose(Image.FLIP_TOP_BOTTOM)
    width, height = img.size
    pixels = list(img.getdata())

    grid_data = []
    for p in pixels:
        # Standard ROS map occupancy calculation
        if negate:
            occ = p / 255.0
        else:
            occ = (255.0 - p) / 255.0

        if p == 205: # Default unknown color in ROS map_saver
            val = -1
        elif occ >= occupied_thresh:
            val = 100
        elif occ <= free_thresh:
            val = 0
        else:
            val = -1
        grid_data.append(val)

    base_name = os.path.splitext(os.path.basename(yaml_path))[0]
    final_map_id = map_id or f"MAP-{base_name.upper()}"
    final_name = name or f"Bản đồ {base_name}"

    out_data = {
        "map_id": final_map_id,
        "name": final_name,
        "floor": floor,
        "resolution": resolution,
        "width": width,
        "height": height,
        "origin_x": origin_x,
        "origin_y": origin_y,
        "grid_data": grid_data,
    }

    os.makedirs(os.path.dirname(os.path.abspath(output_json_path)), exist_ok=True)
    with open(output_json_path, "w", encoding="utf-8") as f:
        json.dump(out_data, f)

    print(f"✅ Đã chuyển đổi thành công ROS 2 Map sang Web JSON:")
    print(f"   - File nguồn: {yaml_path} ({width}x{height}, res={resolution}m)")
    print(f"   - File đích:   {output_json_path}")
    print(f"   - Map ID:      {final_map_id}")
    return out_data

if __name__ == "__main__":
    if len(sys.argv) < 2:
        yaml_file = os.path.join(os.path.dirname(__file__), "..", "maps", "phong_lam_viec.yaml")
    else:
        yaml_file = sys.argv[1]

    name_without_ext = os.path.splitext(os.path.basename(yaml_file))[0]
    backend_maps_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "backend", "static", "maps"))
    dest_json = os.path.join(backend_maps_dir, f"{name_without_ext}.json")
    robot_json = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "maps", f"{name_without_ext}.json"))

    data = convert_nav2_map_to_json(
        yaml_path=yaml_file,
        output_json_path=dest_json,
        map_id=name_without_ext,
        name=f"Bản đồ {name_without_ext.replace('_', ' ').title()}",
    )
    with open(robot_json, "w", encoding="utf-8") as f:
        json.dump(data, f)
    print(f"   - File robot:  {robot_json}")
