import random
from datetime import datetime
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, desc

from app.core.database import get_db
from app.models import Staff, HousekeepingRequest, ManagementDirective
from app.schemas.operations import (
    HousekeepingRequestCreate,
    HousekeepingAssignRequest,
    HousekeepingRequestResponse,
    HousekeepingDashboardResponse,
    StaffResponse,
)
from .shared import TAG_HK, create_department_notification

router = APIRouter()

# 2. HOUSEKEEPING DASHBOARD & REQUESTS
# =====================================================================

@router.get("/dashboard/housekeeping", response_model=HousekeepingDashboardResponse, tags=TAG_HK)
async def get_housekeeping_dashboard(db: AsyncSession = Depends(get_db)):
    """Returns housekeeping requests, floor status, available staff and KPIs."""
    req_res = await db.execute(select(HousekeepingRequest).order_by(desc(HousekeepingRequest.created_at)))
    hk_list = req_res.scalars().all()

    dir_res = await db.execute(
        select(ManagementDirective).where(
            ManagementDirective.department == "Housekeeping"
        ).order_by(desc(ManagementDirective.created_at))
    )
    dir_list = dir_res.scalars().all()

    staff_res = await db.execute(
        select(Staff).where(Staff.department == "Housekeeping", Staff.status != "off_shift")
    )
    available_staff = staff_res.scalars().all()

    unified_hk = []
    for h in hk_list:
        unified_hk.append(
            HousekeepingRequestResponse(
                id=f"REQ-{h.ticket_code}",
                ticket_code=h.ticket_code,
                source=h.source or "From HCRobot",
                time_label=h.time_label or "Recent",
                title=h.title,
                room_number=h.room_number,
                description=h.description,
                guest_name=h.guest_name or "Guest",
                status=h.status,
                assigned_staff_name=h.assigned_staff_name,
                created_at=h.created_at,
            )
        )

    for d in dir_list:
        room_num = d.location.replace("ROOM ", "").replace("Room ", "").replace("Phòng ", "").strip()
        unified_hk.append(
            HousekeepingRequestResponse(
                id=f"REQ-{d.code}",
                ticket_code=d.code,
                source="Operations Directive",
                time_label=d.reported_time_label or "Today",
                title=d.title,
                room_number=room_num or "Main Floor",
                description=d.description,
                guest_name="Operations Admin",
                status=d.status,
                assigned_staff_name=d.assigned_staff_name,
                created_at=d.created_at,
            )
        )

    pending_count = sum(1 for r in unified_hk if r.status in ["Unassigned", "Pending"])
    in_prog_count = sum(1 for r in unified_hk if r.status == "In Progress")
    completed_count = sum(1 for r in unified_hk if r.status == "Completed")
    staff_on_duty_count = len(available_staff)

    kpis = {
        "pendingRequests": pending_count,
        "inProgress": in_prog_count,
        "completedToday": completed_count,
        "staffOnDuty": staff_on_duty_count,
    }

    floor_status = {
        "activeFloor": "FLOOR 5 - ACTIVE",
        "roomsCleaned": 45,
        "totalRooms": 120,
    }

    return {
        "kpis": kpis,
        "requests": unified_hk,
        "floor_status": floor_status,
        "available_staff": available_staff,
    }


@router.post("/housekeeping/requests", response_model=HousekeepingRequestResponse, status_code=status.HTTP_201_CREATED, tags=TAG_HK)
async def create_housekeeping_request(req_in: HousekeepingRequestCreate, db: AsyncSession = Depends(get_db)):
    """Creates a new housekeeping ticket (generated by HCRobot vision or guest request)."""
    ticket_code = f"HK-{random.randint(1044, 9999)}"
    new_req = HousekeepingRequest(
        ticket_code=ticket_code,
        source=req_in.source,
        time_label="Just now",
        title=req_in.title,
        room_number=req_in.room_number,
        description=req_in.description,
        guest_name=req_in.guest_name,
        status="Unassigned",
    )
    db.add(new_req)
    await create_department_notification(
        db=db,
        department="Housekeeping",
        title=f"Yêu cầu Buồng phòng mới #{ticket_code}",
        description=f"Phòng {req_in.room_number}: {req_in.title} - {req_in.description or 'Yêu cầu dọn dẹp'}",
        request_id=new_req.id,
        request_type="housekeeping",
        type="Request",
    )
    await db.commit()
    await db.refresh(new_req)
    return new_req


@router.patch("/housekeeping/requests/{request_id}/assign", response_model=HousekeepingRequestResponse, tags=TAG_HK)
async def assign_housekeeping_request(
    request_id: str,
    assign_in: HousekeepingAssignRequest,
    db: AsyncSession = Depends(get_db),
):
    """Assigns staff or marks housekeeping task in progress."""
    clean_id = request_id.replace("HK-", "").strip()
    res = await db.execute(
        select(HousekeepingRequest).where(
            (HousekeepingRequest.id == request_id) |
            (HousekeepingRequest.ticket_code == request_id) |
            (HousekeepingRequest.id == clean_id) |
            (HousekeepingRequest.ticket_code == clean_id) |
            (HousekeepingRequest.id.ilike(f"%{clean_id}%")) |
            (HousekeepingRequest.ticket_code.ilike(f"%{clean_id}%"))
        )
    )
    req = res.scalar_one_or_none()
    if not req:
        # Fallback search by first HK request if matching by ID fails
        all_hk = await db.execute(select(HousekeepingRequest))
        first_hk = all_hk.scalars().first()
        if first_hk:
            req = first_hk
        else:
            raise HTTPException(status_code=404, detail="Housekeeping request not found")

    req.status = assign_in.status
    req.assigned_staff_name = assign_in.assigned_staff_name

    # Safe Foreign Key lookup: only set assigned_staff_id if valid in Staff table
    if assign_in.assigned_staff_id:
        staff_check = await db.execute(
            select(Staff).where(
                (Staff.id == assign_in.assigned_staff_id) |
                (Staff.username == assign_in.assigned_staff_id) |
                (Staff.full_name == assign_in.assigned_staff_name)
            )
        )
        found_staff = staff_check.scalar_one_or_none()
        req.assigned_staff_id = found_staff.id if found_staff else None
    else:
        req.assigned_staff_id = None

    await db.commit()
    await db.refresh(req)
    return req


